# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

# add pods for desired Firebase products
# https://firebase.google.com/docs/ios/setup#available-pods

target 'Spots' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Spots
  pod 'FirebaseUI/Storage'
  pod 'Firebase/Core'
  pod 'Firebase/Firestore'
  pod 'FirebaseFirestoreSwift'
  pod 'Firebase/Auth'
  pod 'Firebase/Storage'
end
